SET NAMES utf8mb4;
SET @dept_ccis = (SELECT id FROM departments WHERE code = 'CCIS' LIMIT 1);
INSERT IGNORE INTO `subjects` (`code`, `title`, `department_id`, `course`, `year_level`, `section`, `semester`, `school_year`, `catalog_id`) VALUES
('REED 102', 'Ecclesiology', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('REED 102', 'Ecclesiology', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('REED 102', 'Ecclesiology', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('REED 102', 'Ecclesiology', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('NSTP 2', 'National Service Training Program 2', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('NSTP 2', 'National Service Training Program 2', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('NSTP 2', 'National Service Training Program 2', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('NSTP 2', 'National Service Training Program 2', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('ACCTG 1', 'Fundamentals of Accounting', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('ACCTG 1', 'Fundamentals of Accounting', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('ACCTG 1', 'Fundamentals of Accounting', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('PE 2', 'Pathfit 2: Exercised-Based Fitness Activities', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('PE 2', 'Pathfit 2: Exercised-Based Fitness Activities', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('PE 2', 'Pathfit 2: Exercised-Based Fitness Activities', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('PE 2', 'Pathfit 2: Exercised-Based Fitness Activities', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('GEC 2', 'Reading in the Philippine History', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('GEC 2', 'Reading in the Philippine History', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('GEC 2', 'Reading in the Philippine History', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('GEC 2', 'Reading in the Philippine History', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('GEC 6', 'Purposive Communication', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('GEC 6', 'Purposive Communication', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('GEC 6', 'Purposive Communication', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('GEC 6', 'Purposive Communication', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('PROG 2', 'Computer Programming 2', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('PROG 2', 'Computer Programming 2', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('PROG 2', 'Computer Programming 2', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('IAS', 'Information Assurance Security 1', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('IAS', 'Information Assurance Security 1', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('IAS', 'Information Assurance Security 1', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('MUL', 'Multimedia System', @dept_ccis, 'BSIT', '1', '1', '2nd Semester', NULL, NULL),
('GEC ELECT 2', 'Entrepreneurial Mind', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('SPT 02', 'School and Academic Librarianship', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('GEC 9', 'Ethics', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('SPT 03', 'Special and Public Librarianship', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('ICT 102', 'Programming Fundamentals', @dept_ccis, 'BLIS', '1', '1', '2nd Semester', NULL, NULL),
('REED 102', 'Ecclesiology', @dept_ccis, 'BSIT', '1', '2', '2nd Semester', NULL, NULL),
('ACCTG 1', 'Fundamentals of Accounting', @dept_ccis, 'BSIT', '1', '2', '2nd Semester', NULL, NULL),
('PE 2', 'Pathfit 2: Exercised-Based Fitness Activities', @dept_ccis, 'BSIT', '1', '2', '2nd Semester', NULL, NULL),
('GEC 2', 'Reading in the Philippine History', @dept_ccis, 'BSIT', '1', '2', '2nd Semester', NULL, NULL),
('GEC 6', 'Purposive Communication', @dept_ccis, 'BSIT', '1', '2', '2nd Semester', NULL, NULL),
('PROG 2', 'Computer Programming 2', @dept_ccis, 'BSIT', '1', '2', '2nd Semester', NULL, NULL),
('IAS 1', 'Information Assurance Security 1', @dept_ccis, 'BSIT', '1', '2', '2nd Semester', NULL, NULL),
('MUL', 'Multimedia System', @dept_ccis, 'BSIT', '1', '2', '2nd Semester', NULL, NULL),
('DS 1', 'Discrete Structure 1', @dept_ccis, 'BSCS', '1', '1', '2nd Semester', NULL, NULL),
('IPT', 'Integrative Programming', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('IPT', 'Integrative Programming and Technologies', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('IT HCI', 'Human Computer and Interaction', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('IT HCI', 'Human Computer and Interaction', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('IT WEB', 'Web System and Technologies', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('IT WEB', 'Web System and Technologies', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('IT APPDEV', 'Application Development and Emerging Technologies', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('IT APPDEV', 'Application Development and Emerging Technologies', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('PE 4', 'Pathfit 4: Sports', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL),
('PE 4', 'Pathfit 4: Sports', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('PE 4', 'Pathfit 4: Sports', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('PE 4', 'Pathfit 4: Sports', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('PE 4', 'Pathfit 4: Sports', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('REED 104', 'liturgy and Sacraments', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL),
('REED 104', 'liturgy and Sacraments', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('REED 104', 'liturgy and Sacraments', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('REED 104', 'liturgy and Sacraments', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('REED 104', 'liturgy and Sacraments', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('GEC 7', 'Arts Appreciation', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL),
('GEC 7', 'Arts Appreciation', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('GEC 7', 'Arts Appreciation', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('GEC 7', 'Arts Appreciation', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('GEC 7', 'Arts Appreciation', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('GEC 8', 'Life and Works and Rizal', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL),
('GEC 8', 'Life and Works and Rizal', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('GEC 8', 'Life and Works and Rizal', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('GEC 8', 'Life and Works and Rizal', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('GEC 8', 'Life and Works of Rizal', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('IT DM', 'Discrete Mathematics', @dept_ccis, 'BSIT', '2', '1', '2nd Semester', NULL, NULL),
('IT DM', 'Discrete Mathematics', @dept_ccis, 'BSIT', '2', '2', '2nd Semester', NULL, NULL),
('CS HCI', 'Human Computer Interaction', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('CS WEB', 'Web Systems and Technologies', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('CS APPDEV', 'Application Development and Emerging Technologies', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('CS SOFTENG1', 'Software Engineering 1', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('CS OS', 'Operating Systems', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('CS ALGO', 'Algorithm and Complexity', @dept_ccis, 'BSCS', '2', '1', '2nd Semester', NULL, NULL),
('IS HCI', 'Human Computer Interaction', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('IS WEB', 'Web System and Technologies', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('IS APPDEV', 'Application Development and Emerging Technologies', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('IS SAD', 'System Analysis and Design', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('IS OMC', 'Organization and Management Concepts', @dept_ccis, 'BSIS', '2', '1', '2nd Semester', NULL, NULL),
('ISM', 'IT Security and Management', @dept_ccis, 'BSIS', '1', '1', '2nd Semester', NULL, NULL),
('ICT 103', 'System Analysis and Design in Libraries and Information System', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL),
('STAT', 'Advanced Statistics', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL),
('LIS 105', 'Information Resources and Services 2', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL),
('COGNATE', 'Business Communication', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL),
('LIS 106', 'Organization of Information Resources 2', @dept_ccis, 'BLIS', '2', '1', '2nd Semester', NULL, NULL);