<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    private array $deptIdToCode = [
        1  => 'CCIS',
        4  => 'CTE',
        5  => 'CCJE',
        6  => 'CAS',
        7  => 'CBMA',
        8  => 'CTHM',
        14 => 'EDP',
        15 => 'PMO',
        16 => 'Registrar',
        17 => 'Finance',
        18 => 'OSAS',
        19 => 'RIID',
    ];

    public function run(): void
    {
        $this->command->info('Seeding student users and profiles...');

        $deptMap = DB::table('departments')->pluck('id', 'code')->toArray();

        $dept = function (int $oldId) use ($deptMap): ?int {
            $code = $this->deptIdToCode[$oldId] ?? null;
            return $code ? ($deptMap[$code] ?? null) : null;
        };

        // Each entry: [old_user_id, name, email, password, old_dept_id, created_at,
        //               course, year_level, section, student_status, semester, school_year]
        // profile data is taken from student_profiles (id, user_id, dept, course, year_level,
        // section, student_status, semester, school_year)
        $students = [
            // BSIT year 1 section 1
            ['old_user_id' => 115, 'name' => 'Apostadero, Jovie Rose Pines',           'email' => 'joverosapostadero@smccnaspi.edu.ph',          'password' => '$2y$10$Ey0j/Gn9a8lloJSX4110KeDyRwYHgJjGLdJgT/EcPn2Q6WRQzVVHG', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:07:25', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 116, 'name' => 'Arceo, Duke Allej Sison',                'email' => 'dukeallejarceao@smccnaspit.edu.ph',           'password' => '$2y$10$oF.CEXRrW1/CBsp8zoAFN.TI4.j7ywAM67X55kea6JA5Zjnf8KL0e', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:09:13', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 117, 'name' => 'Avis, Mike Denver Pagador',              'email' => 'mikedenveravis@smccnasipit.edu.ph',           'password' => '$2y$10$brnevpXSePfAjm5ulvL.MOWDxAhM811cfm/8pYkgfkPQwFgw0sxha', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:09:59', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 118, 'name' => 'Barajan, Ana Cristher Ilustrisimo',      'email' => 'anacristherbarajan@smccnasipit.edu.ph',       'password' => '$2y$10$pW3z/bOKiLHNrjUaCG.wCe44JjGhuehrB.AQBjJwu0aI.kQoO2VEm', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:10:55', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 119, 'name' => 'Belegaño, Cheryl Zaspa',                 'email' => 'charylbelegano@smccnasipit.edu.ph',           'password' => '$2y$10$61gen2k3H3c6nmFB4V5oH.IuVfr.iHQc5YWliYe9FAYjMqy5DQgyC', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:11:46', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 120, 'name' => 'Bongocan, Michael Barbarona',            'email' => 'michaelbongocan@smccnasipit.edu.ph',          'password' => '$2y$10$aRizUAVZvpMO750ck9bxIe4O/Ru9QotirKVMfcl//Ku/FR3KVbWBa', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:12:32', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 121, 'name' => 'Bravo, Jico Artigo',                     'email' => 'jicobravo@smccnasipit.edu.ph',                'password' => '$2y$10$wnHC8E/VBVZyty.qPydPgOU6T9FumUzPYKf6P3L0i.NtNA4uoDTuq', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:13:20', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 122, 'name' => 'Brigole, Geo Jalandoni',                 'email' => 'geobrigole@smccnasipit.edu.ph',               'password' => '$2y$10$ZBbD/bKhFvD8rmn1RxEsYOlY5B6QDdbIb6CNmLeFT79jmhE7ZftfW', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:14:04', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 123, 'name' => 'Bulasa, Arvin Culaba',                   'email' => 'arvinbulasa@smccnasipit.edu.ph',              'password' => '$2y$10$6N0XfjIp5pxwMUoG1LO4suYEx5E/UK5NP1vpayxik0qPEZeCj3l1K', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:14:37', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 124, 'name' => 'Butao, Judy Ann Samayla',                'email' => 'judyannbutao@smccnasipit.edu.ph',             'password' => '$2y$10$K8dAZsbncMc/ITwA5ZoxLuH3k8pvFtYAEd70W96tCrZgCZHqwpxti', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:15:16', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 125, 'name' => 'Cano, Lea Carmina Salfamonis',           'email' => 'learcarminacano@smccnasipit.edu.ph',          'password' => '$2y$10$RC4.SGRbRU8NMo77s47.t.Z40ueG8wAryRwmkNPMZErNfX8yLSgQO', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:15:47', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 126, 'name' => 'Casinao, Reymark Napone',                'email' => 'reymarkcasinao@smccnasipit.edu.ph',           'password' => '$2y$10$ZFCPtIV2U2TpJ.LQlnH1be8i8LjTMK0kO3weBEk8uwqtokrcSb4yy', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:16:27', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 127, 'name' => 'Cordero, Johnbert Acero',                'email' => 'johnbertcordero@smccnasipit.edu.ph',          'password' => '$2y$10$qtUo/QQuusidMna0V82Vve07/rSyFWCclsnvwTeJEUJy55EQxX.dO', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:17:06', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 128, 'name' => 'Dadang, Newnyl Lao',                     'email' => 'newnyldadang@smccnasipit.edu.ph',             'password' => '$2y$10$6whPXT0Te2hdz14CFvy1FuNm7Te63jMtx7um/zWjm/6ZcUB/wCr5C', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:17:44', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 129, 'name' => 'Dagaas, Jason Web Embay',                'email' => 'jasonwebdagaas@smccnasipit.edu.ph',           'password' => '$2y$10$HDWfcMKBhDIvxWILf/eKbu.OMHP.p/q86oTmwEcaL3eco2XD/.ro.', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:18:30', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 130, 'name' => 'Domino, Rodelyn Bustillo',               'email' => 'rodelyndomino@smccnasipit.edu.ph',            'password' => '$2y$10$qxblx/uMbxXPAfQiig1Ox.3220IbxDqFBdYSBZyRomjjhwXltXNRS', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:19:12', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 131, 'name' => 'Ebarle, Pamela Ann Sarmiento',           'email' => 'pamelaannebarle@smccnasipit.edu.ph',          'password' => '$2y$10$YTkMSbtGLKyPJ6rx51z2PupHu6SjyBoS6OdE2npNhY689PcZqhyia', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:20:03', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 132, 'name' => 'Escaran, Rhona Jane Daarol',             'email' => 'rhonajaneescaran@smccnasipit.edu.ph',         'password' => '$2y$10$xSVv8pNcvwJgE7IwoXFRuu7u1.zcEqvSqv6h.Fm4ZDsamwv0cbjDi', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:20:51', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 133, 'name' => 'Estemera, Paul Ervin Coyoca',            'email' => 'paulervinestemera@smccnasipit.edu.ph',        'password' => '$2y$10$hE3Jgf5pKWPGNiDujMdbz.tz46dwLX5xXcMEX53AD5vKbEoWFFcL.', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:21:29', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 134, 'name' => 'Galenia, Justine Estan',                 'email' => 'jutinegalenia@smccnasipit.edu.ph',            'password' => '$2y$10$E.bPKSxEfvLtrBpZgzfkpeCasoQ4FwUtu9S5ZE2DLPhJ60q9qkE2m', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:22:28', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 135, 'name' => 'Gavia, Aike Ryan',                       'email' => 'aikeryangavia@smccnasipit.edu.ph',            'password' => '$2y$10$TT9/TrcTUpYBI6gwzapM1eWWOKDxAqEuvkmqYCY5HcPs1cfGFRzWC', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:23:06', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 136, 'name' => 'Jaminal, Neil Zachary Perame',           'email' => 'neilzacharyjaminal@smccnasipit.edu.ph',       'password' => '$2y$10$8hqy5yf5ohP2HMt6X203mu11OZYgRag.UT4dd9tQzOHn5mdcRFZ66', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:23:51', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 137, 'name' => 'Labador, Recarte Revero',                'email' => 'recartelabador@smccnasipit.edu.ph',           'password' => '$2y$10$HiHoJihhPrrOsq0tGHEUxesz/OOWW4waJHMEHKxT2JetHVCsYdR0q', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:24:27', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 138, 'name' => 'Lagrante, Vinaya Bianca Caseres',        'email' => 'venayabiancalagrante@smccnasipit.edu.ph',     'password' => '$2y$10$keCVJN8wKC6QL5ZUZmaV.eYGdz7aVzjU1ylHxCJPwo4LI3UswSG5.', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:25:05', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 139, 'name' => 'Lanticse, Jade Mark Cajegas',            'email' => 'jademarklanticse@smccnasipit.edu.ph',         'password' => '$2y$10$Xx.GMnNAzJDvxzUlYt8KX.SOBZz0ugqdWmkRVL35ZsRv.ojs8p9IK', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:25:41', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 140, 'name' => 'Lumayno, Jhon Dexter Cordova',           'email' => 'jhondexterlumayno@smccnasipit.edu.ph',        'password' => '$2y$10$GyljRuSeecAnc9jIvSHWhO8C33eQIUl13NqoDS4ctbI230AGVmywu',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:26:19', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 141, 'name' => 'Magallanes, Apple Mae Salonoy',          'email' => 'applemaemagallanes@smccnasipit.edu.ph',       'password' => '$2y$10$K3fb7U6cDudakbYqgQetq.mupPXpATzqUwFCXG/MquzzDHsOxipf2', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:26:55', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 142, 'name' => 'Martin, Ceazarina Heart Paler',          'email' => 'ceazarinaheartmartin@smccnasipit.edu.ph',     'password' => '$2y$10$5R1Wy7runNBWq0JAjqW1h.tedygWVQQQsLAjcdHjUsHRNYnWj0EX.',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:27:42', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 143, 'name' => 'Narte, Raiden Paul Laganga',             'email' => 'raidenpaulnarte@smccnasipit.edu.ph',          'password' => '$2y$10$FVoYhu2a625mgE8MkwK0x.zpxcMRrnBQPbmT1hvXwlpbpbwZmnD7m', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:28:21', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 144, 'name' => 'Olar, Chris Lawrence Felicilda',         'email' => 'chrislawrenceolar@smccnasipit.edu.ph',        'password' => '$2y$10$DR.wOEynGUhddpqr6v1afukc.8vPB8.1zx.FAqHuwdkU2qWaBIPTy', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:29:12', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 145, 'name' => 'Palco, Raiza Kasandra Lucino',           'email' => 'raizakasandrapalco@smccnasipit.edu.ph',       'password' => '$2y$10$tv1yL1N8MOS4I0if8rbAweqYSjqwx2xGnskEfoYmJmHkrMKytdM12', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:29:44', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 146, 'name' => 'Rubillos, Roger Jugarap',                'email' => 'rogerrubillos@smccnasipit.edu.ph',            'password' => '$2y$10$7VQzJk9jf5EcuuF5FCQ3GOXUi8cw4bWa.Ip8o2cRIj1ygSMpvfWde', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:30:51', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 147, 'name' => 'Salfamonis, Cristel Nadonga',            'email' => 'cristelsalfamonis@smccnasipit.edu.ph',        'password' => '$2y$10$ERlI5H4B4WIgjeZBuspoqeqqT48rxC9pdNkVSRQG2avuSFNIsVTAG', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:31:48', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 148, 'name' => 'Torregosa, Louegie Fuego',               'email' => 'louegietorregosa@smccnasipit.edu.ph',         'password' => '$2y$10$0YXb0nWshNVasGBdtuq98.EObVJo6z.x4VRMVQ8hF6VStRFGIW.u.',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:32:26', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 149, 'name' => 'Tumala, Rheapearl Manguiob',             'email' => 'rheapearltumala@smccnasipit.edu.ph',          'password' => '$2y$10$/246WvNKfXeApX1utdy6GOWX1e4BqYeWbKEuj.MV25yVf15AZG52q', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:33:29', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 150, 'name' => 'Vallar, Alyza Kaye Devivar',             'email' => 'alyzakayevallar@smccnasipit.edu.ph',          'password' => '$2y$10$XwKaZh8f.LGmkDDvKq1MYOckFaeWjOaDPrBAkTYP8LwMBYTMXCd6W', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:34:11', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 151, 'name' => 'Valleser, Laurence Bolonias',            'email' => 'laurencevalleser@smccnasipit.edu.ph',         'password' => '$2y$10$dZg6uXltx3FpFMjD/iy2Duy4VmxFL4jyXmmgXD/D2lZvxiA5OM45K', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:35:04', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 152, 'name' => 'Viajar, Alexandra Julie Juera',          'email' => 'alexandrajulieviajar@smccnasipit.edu.ph',     'password' => '$2y$10$5mvLQ2fIVh47WUMjWmF9l.UzE9RazG7skeDogRnJR/6V3usexN1Ge', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:35:42', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 153, 'name' => 'Villamor, Ronnie Cordova',               'email' => 'ronnievillamor@smccnasipit.edu.ph',           'password' => '$2y$10$N7xBRVWKsVHaY7XdCojmB.IVSlIrNEX16BQpWInScpphD/KWFIPpW', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:36:22', 'course' => 'BSIT', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            // BSCS year 1 section 1
            ['old_user_id' => 154, 'name' => 'Albarico, Ailene Vic -',                 'email' => 'ailenealbarico@smccnasipit.edu.ph',           'password' => '$2y$10$K3x.bttPiJynqe6fEJwk6OSVbtV2h6HnW35iUiQDsGr0HbfQK6crO', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:38:45', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 155, 'name' => 'Algarme, Clark Justin Sale',             'email' => 'clarkjustinalgarme@smccnasipit.edu.ph',       'password' => '$2y$10$0qlNMtDQM3AMYKuqHE6Nr.dZVMrkwu6IuIC9iB8oHhJw8uSUOgGCa', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:39:19', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 156, 'name' => 'Alibanggo, Antonette Regner',            'email' => 'antonettealibanggo@smccnasipit.edu.ph',       'password' => '$2y$10$Le7G11tM51J.myxrw34zBeuijq584GO6jpWwPigBb/O8iMpye2Ugi',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:39:52', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 157, 'name' => 'Ampiyawan, Hechel Sulhayan',             'email' => 'hechelampayawan@smccnasipit.edu.ph',          'password' => '$2y$10$Y0oVuDonfdcmUvJOkdTg/OYSHZRoBUvv9XTnQnV60Q7rmKFLpzD/u', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:40:52', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 158, 'name' => 'Baguio, Althea Sheine Labor',            'email' => 'altheasheinebaguio@smccnasipit.edu.ph',       'password' => '$2y$10$XYSXu8O2bOTFO5tExAl1TulwJgtLaeWlwLiHCOKj/f4SO5i85OSlS', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:41:28', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 159, 'name' => 'Berandal, Stephanie Empuesto',           'email' => 'stephanieberandal@smccnasipit.edu.ph',        'password' => '$2y$10$ZeApRwRBH4VOrBL3gO0The2PBn3OvHk/61iaxvKH1s7YuR2JLazR6', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:42:07', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 160, 'name' => 'Caila, John Michael Maglasang',          'email' => 'johnmichaelcaila@smccnasipit.edu.ph',         'password' => '$2y$10$OXbA7VAebxF1xFZWLvwNcedNkT3o0euoZVrMLJqjDf6xpcqWo.y5.',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:42:45', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 161, 'name' => 'Canales, Cindy Suazo',                   'email' => 'cindycanales@smccnasipit.edu.ph',             'password' => '$2y$10$HfmmYR.Vg0Tp52jzab5L.OhoPeWJUNvSzps/mi07NahiAMTcEMM0q', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:43:15', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 162, 'name' => 'Caratao, Princess May Rodicol',          'email' => 'princessmaycaratao@smccnasipit.edu.ph',       'password' => '$2y$10$5p6ep.iNWO1MFQ02LtrnpOatI3LUO2xTxfRkm9eEJGL5ROypC4IN2', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:44:03', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 163, 'name' => 'Carvajal, Gecko Ferolino',               'email' => 'geckocarvajal@smccnasipit.edu.ph',            'password' => '$2y$10$mHLoSYAlGz3ADzwxw/x.QuoWaR7c2cwaP2XbsSZXz03czmk8epYtC', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:44:47', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 164, 'name' => 'Cinco, Crystal Jane Salomon',            'email' => 'crystaljanecinco@smccnasipit.edu.ph',         'password' => '$2y$10$solMkup0lyPN6CicKENcTeDPltSjbbUFMRgWlbi/pjZbvGHHzCtwq',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:45:26', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 165, 'name' => 'Damo-Ag, Jesa Mae Omblero',              'email' => 'jesamaedamoag@smccnasipit.edu.ph',            'password' => '$2y$10$nUHu7lLm0uYYKZPhy6HR.umhW9TB4Sktkep3755Z1hRWTvPT8.Xc.',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:46:00', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 166, 'name' => 'Domosmog, Justine Sanico',               'email' => 'justinedomosmog@smccnasipit.edu.ph',          'password' => '$2y$10$iot1E.wQgbb8KmOLBLs.RuCfxhx6TPmi5Y.6FxBq4mkDKVXy1MJ7O', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:46:45', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 167, 'name' => 'Eder, Gheian Lagare',                    'email' => 'gheianeder@smccnasipit.edu.ph',               'password' => '$2y$10$bl8QAbwUWKST/LOOzvAtWep.t7m9aX9Ve6Tid8dpifoCVeLLjKBg6',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:47:16', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 168, 'name' => 'Flores, Michelle Leslie Dela Victoria',  'email' => 'michelleleslieflores@smccnasipit.edu.ph',     'password' => '$2y$10$VK6cVvw4BVf1Bdf8ED4JfuXX5lVWFjhboe9jVEFdXuLDDQIiFXvEm', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:48:20', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 169, 'name' => 'Japson, Xynette Thea Malicdem',          'email' => 'xynettetheajapson@smccnasipit.edu.ph',        'password' => '$2y$10$QSwoXcpLc1pCsIFQ6k5aru/Rs/O3n117XQJZ15Yu0AkcXUoXBaTgy', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:48:59', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 170, 'name' => 'Maamo, Christian Ace Montejo',           'email' => 'christianacemaamo@smccnasipit.edu.ph',        'password' => '$2y$10$ZYSLFGCX7z.jybrrr.CJW.b04GRkkEkh.doxXjZWs5iK2alh5Tbl2', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:49:34', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 171, 'name' => 'Mabitado, Rixk Alba',                    'email' => 'rixkmabitado@smccnasipit.edu.ph',             'password' => '$2y$10$Sw2wx8l9tGrfKTR/14RKvuKUvaY7hHAWVMa4rVGuIAkKblaSJvOam', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:50:29', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 172, 'name' => 'Mondejar, Dean Stuart Babayson',         'email' => 'deanstuartmondejar@smccnasipit.edu.ph',       'password' => '$2y$10$xU0KGdX41F6eu70jibTp7uNPOYvVahtqkzkvvbwYqW5e7rvCuaIYi', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:51:00', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 173, 'name' => 'Olaco, Carlos Miguel Flores',            'email' => 'carlosmiguelolaco@smccnasipit.edu.ph',        'password' => '$2y$10$5eLKUyhopFUGbRT3zn6LOOOPIzRKl1CZLjIAJP5uE1EDk5ymRyid2', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:51:43', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 174, 'name' => 'Rabino, Brendon Ationg',                 'email' => 'brendonrabino@smccnasipit.edu.ph',            'password' => '$2y$10$KwlNyI60kcm5XoawxSd/aeTSStlE9azDGB1VcUgQF8ldJl4Lqmmum', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:54:19', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 175, 'name' => 'Ratilla, July Mae Pable',                'email' => 'julymaeratilla@smccnasipit.edu.ph',           'password' => '$2y$10$9M1PFvXOrIoOH6HT.t5ZEeVrV5qksWYKN9YaP3N02bk8be5JGMAyy', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:55:02', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 176, 'name' => 'Relosa, Rezza Mae Densing',              'email' => 'rezzamaerelosa@smccnasipit.edu.ph',           'password' => '$2y$10$sjk6a/O5WeQJlwKjjXIaROdr/zThTZChf.O0cJb3RL4uQj3eo1356',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:56:30', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 177, 'name' => 'Rotante, Limuel Tampos',                 'email' => 'limuelrotante@smccnasipit.edu.ph',            'password' => '$2y$10$KhKCt.lubwHJ2oT9kfFyT.b6AifirN7WXH8HhGMbU.1WOL8i/a/P2', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:57:23', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 178, 'name' => 'Salga, Nikko Langilao',                  'email' => 'nikkosalga@smccnasipit.edu.ph',               'password' => '$2y$10$.t.JT52BXh1QX/eA5RQmWewkDl6RZ6XDdXBeIbWHv6v0uoufCu3k.',  'old_dept_id' => 1, 'created_at' => '2026-03-22 13:57:58', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 179, 'name' => 'Salinay, Justen Sulhayan',               'email' => 'justensalinay@smccnasipit.edu.ph',            'password' => '$2y$10$Mj32PKsUAAbbX1qMm.8GGuEqzr3xwdvt0BRBhBU4HNYiO3.fmE7g2', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:58:26', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 180, 'name' => 'San Agustin, Ced Jedrick Soroysoroy',    'email' => 'cedjedricksanagustin@smccnasipit.edu.ph',     'password' => '$2y$10$D17RyfCwmJWjuJbB7C9Vae7CP9cGf8Kx/1Adye1bszf/U3pvERYTi', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:59:06', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
            ['old_user_id' => 181, 'name' => 'Taghoy, Arnolex Ranex',                  'email' => 'arnolextaghoy@smccnasipit.edu.ph',            'password' => '$2y$10$7N3Krl/9YW.WAfD8/ra9rOAIxWlIUVz9wlasPxuRrR7QvBIWJEOHG', 'old_dept_id' => 1, 'created_at' => '2026-03-22 13:59:42', 'course' => 'BSCS', 'year_level' => '1', 'section' => '1', 'student_status' => 'regular', 'semester' => '2nd Semest', 'school_year' => '2025-2026'],
        ];

        $userInserts    = [];
        $profileInserts = [];
        $now            = now()->toDateTimeString();

        foreach ($students as $row) {
            $userId = DB::table('users')->insertGetId([
                'name'                 => $row['name'],
                'email'                => $row['email'],
                'password'             => $row['password'],
                'role'                 => 'student',
                'is_active'            => true,
                'department_id'        => $dept($row['old_dept_id']),
                'must_change_password' => false,
                'created_at'           => $row['created_at'],
                'updated_at'           => $row['created_at'],
            ]);

            DB::table('student_profiles')->insert([
                'user_id'                    => $userId,
                'department_id'              => $dept($row['old_dept_id']),
                'course'                     => $row['course'],
                'year_level'                 => $row['year_level'],
                'section'                    => $row['section'],
                'student_status'             => $row['student_status'],
                'semester'                   => $row['semester'],
                'school_year'                => $row['school_year'],
                'last_promoted_school_year'  => null,
                'last_promoted_semester'     => null,
                'created_at'                 => $row['created_at'],
            ]);
        }

        $this->command->info('Seeded ' . count($students) . ' students with profiles.');
    }
}
